# -------------------------------------------------------
#
# Syntax
#
# -------------------------------------------------------
[[plugins]]
repo = 'pboettch/vim-cmake-syntax'
on_ft = ['cmake']

[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']

[[plugins]]
repo = 'asciidoc/vim-asciidoc'
on_ft = ['asciidoc']

[[plugins]]
repo = 'sudar/vim-arduino-syntax'
on_ft = ['arduino']

[[plugins]]
repo = 'taketwo/vim-ros'
on_ft = ['roslaunch']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']



# -------------------------------------------------------
#
# Development
#
# -------------------------------------------------------
[[plugins]]
repo = 'jpalardy/vim-slime'
on_ft = ['python']

[[plugins]]
repo = 'hanschen/vim-ipython-cell'
on_ft = ['python']



# -------------------------------------------------------
#
# deoplete
#
# -------------------------------------------------------
[[plugins]]
repo = 'Shougo/deoplete.nvim'
rev = '5.0'
on_event = 'InsertChartPre'
hook_source = '''
  let g:python3_host_prog = '/usr/bin/python3'
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#auto_complete_delay = 0
  let g:deoplete#auto_complete_start_length = 1
  let g:deoplete#enable_camel_case = 0
  let g:deoplete#enable_ignore_case = 0
  let g:deoplete#enable_refresh_always = 0
  let g:deoplete#enable_smart_case = 1
  let g:deoplete#file#enable_buffer_path = 1
  let g:deoplete#max_list = 10000
'''
on_i = 1
