#
# Vim8をNeoVim対応にする
#
[[plugins]]
if = "!has('nvim')"
repo = 'roxma/nvim-yarp'
[[plugins]]
if = "!has('nvim')"
repo = 'roxma/vim-hug-neovim-rpc'

#
# UI for dain update
#
[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

#
# Formatter
#
#[[plugins]]
#repo = 'Chiel92/vim-autoformat'


#
# Completion
#
[[plugins]]
repo = 'Shougo/ddc.vim'
[[plugins]]
repo = 'shun/ddc-vim-lsp'
hook_add = '''
  call ddc#custom#patch_global('sources', ['vim-lsp'])
  call ddc#custom#patch_global('sourceOptions', {
      \ 'vim-lsp': {
      \   'matchers': ['matcher_head'],
      \   'mark': 'lsp',
      \ },
      \ })

  " if you want to use the unsupported CompleteProvider Server,
  " set true by'ignoreCompleteProvider'.
  call ddc#custom#patch_filetype(['css'], {
     \ 'sourceParams': {
     \   'vim-lsp': {
     \     'ignoreCompleteProvider': v:true,
     \   },
     \ },
     \ })
'''
[[plugins]]
repo = 'Shougo/ddc-around'
[[plugins]]
repo = 'vim-denops/denops.vim'


#
# Git wrapper plugin
#
[[plugins]]
repo = 'tpope/vim-fugitive'


#
# Status bar plugins
#
[[plugins]]
depends = ['vim-airline-themes', 'fugitive.vim']
hook_add = '''
    let g:airline#extensions#tabline#enabled = 1
    let g:airline#extensions#tabline#formatter = 'unique_tail_improved'
    " C-p や C-n でバッファの切り替えを行い, タブ移動を可能にする
    nmap <C-p> <Plug>AirlineSelectPrevTab
    nmap <C-n> <Plug>AirlineSelectNextTab
'''
repo = 'vim-airline/vim-airline'
[[plugins]]
hook_add = '''
    let g:airline_theme='simple'
'''
repo = 'vim-airline/vim-airline-themes'


#
# vim lsp
#
[[plugins]]
hook_add = '''
"    autocmd BufWritePre * call execute('LspDocumentFormatSync')
'''
repo = 'prabirshrestha/vim-lsp'
[[plugins]]
hook_add = '''
   " Enable flake8
   let g:lsp_settings = {
   \   'pylsp-all': {
   \     'workspace_config': {
   \       'pylsp': {
   \         'configurationSources': ['flake8'],
   \         'plugins': {
   \           'flake8': {
   \             'enabled': 1
   \           },
   \           'mccabe': {
   \             'enabled': 0
   \           },
   \           'pycodestyle': {
   \             'enabled': 0
   \           },
   \           'pyflakes': {
   \             'enabled': 0
   \           },
   \         }
   \       }
   \     }
   \   }
   \ }
'''
repo = 'mattn/vim-lsp-settings'

[[plugins]]
hook_add = '''
    let g:UltiSnipsExpandTrigger = '<tab>'
    let g:UltiSnipsJumpForwardTrigger = '<tab>'
    let g:UltiSnipsJumpBackwardTrigger = '<s-tab>'
'''
on_ft = ['tex']
repo = 'lervag/vimtex'

[[plugins]]
on_ft = ['cmake']
repo = 'pboettch/vim-cmake-syntax'

[[plugins]]
on_ft = ['asciidoc']
repo = 'asciidoc/vim-asciidoc'

[[plugins]]
on_ft = ['arduino']
repo = 'sudar/vim-arduino-syntax'

[[plugins]]
on_ft = ['toml']
repo = 'cespare/vim-toml'

[[plugins]]
hook_add = '''
let g:rustfmt_autosave = 1
'''
on_ft = ['rust', 'toml']
repo = 'rust-lang/rust.vim'
